# Generated by Django 5.1.7 on 2025-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('off_duty', models.FloatField()),
                ('sleeper_berth', models.FloatField()),
                ('driving', models.FloatField()),
                ('on_duty', models.FloatField()),
            ],
        ),
    ]
